interface actions{
    SET_PRODUCT : String
    SELECTED_PRODUCT : String
    REMOVE_SELECTED_PRODUCTS : String
}

export const ActionTypes :actions = {
    SET_PRODUCT : "SET_PRODUCT",
    SELECTED_PRODUCT : "SELECTED_PRODUCT",
    REMOVE_SELECTED_PRODUCTS : "REMOVE_SELECTED_PRODUCTS"
}